name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/profile-service-superfs:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/profile-service-superfs:latest

  deploy-to-minikube:
    needs: build-and-push
    runs-on: self-hosted   # <-- runs on your PC (self-hosted runner)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Minikube
        run: |
          kubectl apply -f profile-service-superfs.yaml
          kubectl rollout status deployment/profile-service-superfs
